upload:
  base_dir: <%= Dir.home %>/stories
  file_name: upload_stories.csv

image_upload:
  base_dir: <%= Dir.home %>/images
  file_name: upload_images.csv

illustration:
  storage: fog
  path: path

logo:
  storage: fog
  path: logo_path
 
profile_image:
  storage: fog
  path: profile_image_path

donor_logo:
  storage: fog
  path: donor_logo_path

profile_image:
  storage: fog
  path: profile_image_path

blog_post_image:
  storage: fog
  path: blog_post_image_path

banner_image:
  storage: fog
  path: banner_image_path

ckeditor_assets:
  storage: fog
  path: public_url

category_banner:
  storage: fog
  path: category_banner_path

category_home_image:
  storage: fog
  path: category_home_image_path


fog:
  host: http://localhost:3000/system/story-weaver
  directory: system/story-weaver
  local_host: http://localhost:3000/system/story-weaver
  local_directory: system/story-weaver
  path: illustrations/:id/:style/:basename.:extension
  logo_path: publishers/logos/:id/:style/:basename.:extension
  donor_logo_path: donors/logos/:id/:style/:basename.:extension
  profile_image_path: users/profile_images/:id/:style/:basename.:extension
  blog_post_image_path: blog_posts/blog_post_image/:id/:style/:basename.:extension
  banner_image_path: banners/banner_image/:id/:style/:basename.:extension
  crop_path: illustration_crops/:id/:style/:basename.:extension
  ck_picture_path: ckeditor_assets/pictures/:id/:style/:basename.:extension
  ck_attachment_path: ckeditor_assets/attachments/:id/:filename
  category_banner_path: categories/banners/:id/:style/:basename.:extension
  category_home_image_path: categories/home_images/:id/:style/:basename.:extension


varnam:
  url: https://api.varnamproject.com/

facebook:
  app_id: "782745738484335"
  secret_key: "3635eafa7a0191a0cb8912c1fa04edbb"

google:
  app_id: "916304538455-sog91kfn967vmiu46f4ub1a38q1g3kvp.apps.googleusercontent.com"
  secret_key: "_WpqoKLPgCE2Qjum8HMblKoW"

analytics:
  tracking_id: a_tracking_id

per_page:
  entity_count: 24

org_info:
  prefix: "SW"
  url: "https://storyweaver.org.in"